# Project Information
site_name: Pharmbio Python Package
site_url: https://pharmbio.github.io/pharmbio_package/
site_description: Pharmbio Python Package Documentation
site_author: "Nima Chamyani"
repo_url: https://github.com/pharmbio/pharmbio_package
repo_name: pharmbio_package
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 - Pharmaceutical Bioinformatics Research Group, Uppsala University, Sweden

theme:
  name: material
  language: en
  logo: assets/pharmbio_package_tp.png
  favicon: assets/favicon_64x64.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.footer
    - content.action.edit
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - announce.dismiss
    - content.action.view
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.share
    - toc.follow

# Navigation Structure
nav:
  - Home: index.md
  - Getting Started: 
    - getting_started/index.md
    - getting_started/installation.md
    - getting_started/basic_usage.md
  - User Guide:
    - user_guide/index.md
    - user_guide/configuration.md
    - user_guide/default_usage.md
    - user_guide/avanced_usage.md
    - API Reference:
      - user_guide/api/index.md
      - user_guide/api/config.md
      - user_guide/api/logger.md
      - user_guide/api/utils.md
      - user_guide/api/data_processing.md
      - user_guide/api/database.md
      - user_guide/api/dataset.md
      - user_guide/api/visualization.md
    - Integration: user_guide/integration/index.md
    - Troubleshooting: user_guide/troubleshooting/index.md
  - Contributing Guide:
    - contribution_guide/index.md
  - Release Notes:
    - release_notes/index.md


  - Blog:
      - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pharmbio/pharmbio_package
      name: Pharmbio

plugins:
  - blog:
      enabled: true
      blog_dir: blog
      authors: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
# Build Settings
use_directory_urls: true
