authors:
  nimachamyani:
    name: Nima Chamyani
    description: Creator
    avatar: https://github.com/pharmbio/pharmbio-web/blob/ae745b4fb379403187ce28d7c26c38f738de4c19/static/img/people/nima_200px.jpeg